name: ci

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        # all major version
        version:
          - podman: 4.0.3
            flavor: |
              latest=false
          - podman: 4.1.1
            flavor: |
              latest=false
          - podman: 4.2.1
            flavor: |
              latest=false
          - podman: 4.3.1
            flavor: |
              latest=true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: ${{ matrix.version.flavor }}
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,value=v${{ matrix.version.podman }},pattern={{version}}
            type=semver,value=v${{ matrix.version.podman }},pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            PODMAN_VERSION=${{ matrix.version.podman }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
