name: ci

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        # all major version
        podmanVersion:
          - 4.0.3
          - 4.1.1
          - 4.2.1
          - 4.3.0

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
            prefix=
            suffix=
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,value=v${{ matrix.podmanVersion }},pattern={{version}}
            type=semver,value=v${{ matrix.podmanVersion }},pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            PODMAN_VERSION=${{ matrix.podmanVersion }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
